<?php
$servername = "polaznik02.edunova.hr";
$username = "edunova";
$password = "edunova";

$dbname = "edunovapp20";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

$sql = "SELECT sifra, osoba, iban FROM predavac";
$result = $conn->query($sql);

if ($result->num_rows > 0) {
    // output data of each row
    while($row = $result->fetch_assoc()) {
        echo "<br> Šifra: ". $row["sifra"]. " - Ime: ". $row["osoba"]. " " . $row["iban"] . "<br>";
    }
} else {
    echo "0 results";
}

$conn->close();
?>