ćaoooo

<?php

echo $ime . ' ' . $prezime;

?>
<br>
ovo je bio samo test
<br>
<h1> GRUPA </h1>

<?php
$servername = "polaznik02.edunova.hr";
$username = "edunova";
$password = "edunova";

$dbname = "edunovapp20";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

$sql = "SELECT naziv, smjer, brojpolaznika FROM grupa";
$result = $conn->query($sql);

if ($result->num_rows > 0) {
    // output data of each row
    while($row = $result->fetch_assoc()) {
        echo "<br> Naziv grupe: ". $row["naziv"]. " - Smjer: ". $row["smjer"]. "- Broj polaznika: " . $row["brojpolaznika"] . "<br>";
    }
} else {
    echo "0 results";
}

$conn->close();
?>