<h1>Ovo su smjetovi izlistani iz baze</h1>

<?php
$servername = "polaznik02.edunova.hr";
$username = "edunova";
$password = "edunova";

$dbname = "edunovapp20";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

$sql = "SELECT naziv, trajanje, cijena FROM smjer";
$result = $conn->query($sql);

if ($result->num_rows > 0) {
    // output data of each row
    while($row = $result->fetch_assoc()) {
        echo "<br> Naziv: ". $row["naziv"]. " - Trajanje: ". $row["trajanje"]. "     -Cijena: " . $row["cijena"] . "<br>";
    }
} else {
    echo "0 results";
}

$conn->close();
?>